var map,
    camWidth = 384,
    camHeight = 224,
    player,
    key,
    haveKey,
    cursors,
    jumpingFlag,
    attackingflag = true,
    enemies,
    skeletonRising = true,
    cam,
    weapons,
    playerHealth,
    playerMagicAbility,
    crouch,
    maximumHealth = 3,
    hellBeastBurn = 3,
    healthRestart = maximumHealth;

var ground,
    wall,
    impalement,
    groundFloat,
    invisibleWallLeft,
    invisibleWallRight,
    sureGround,
    doors,
    doorOpen,
    doorClose,
    building;

var losesLifeOverlap = true,
    bullets,
    bullet,
    enemyBullets,
    enemyBullet,
    bulletDistance,
    enemyAttackingflag = true,
    maximumBullets = 3,
    bulletsReload = maximumBullets;

var potions,
    potionsArray = [],
    barrels,
    barrelsArray = [],
    coins,
    coinsArray = [],
    hearts,
    heartsArray = [],
    objectFloat,
    objectFloats = [],
    objectFloatsPoints,
    score = 0,
    scoreText = null,
    enemyCoins,
    enemyCoinsArray = [];